// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmhzvxqvfbhicvjetznl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtaHp2eHF2ZmJoaWN2amV0em5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NjUzNzYsImV4cCI6MjA2NzU0MTM3Nn0.1R02Sz1xzNwXeprxXfZ2KY96AWXp6lzDN6S0GDZT5jA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});